### ISSUE TITLE
B - Game GUI style

### ISSUE THREAD

**Issue by bERBMorais** [BrunoM24/project-sokoban#25]
Now that the basic mechanics seem stable, we should introduce a main menu with a consistent UI. The asset pack we will be using for this is:

https://www.kenney.nl/assets/pixel-ui-pack

![image](https://user-images.githubusercontent.com/32168856/68210619-ccbfa100-ffcd-11e9-82d2-7f0bf2f5fa93.png)

**Comment by BrunoM24** [comment]
Done!
