### ISSUE TITLE
B1 - Visuals

### ISSUE THREAD

**Issue by bERBMorais** [BrunoM24/project-sokoban#26]
As stated in the [epic](https://github.com/BrunoM24/project-sokoban/issues/25), the assets to use will be 

![image](https://user-images.githubusercontent.com/32168856/68210736-0e504c00-ffce-11e9-9750-f7258c096a71.png)

This task contemplates the setting up of the cursor, and UI theme in Godot

**Comment by BrunoM24** [comment]
Done!
